// <auto-generated />
namespace OnlineShoppingMvcApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class shopping11111 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(shopping11111));
        
        string IMigrationMetadata.Id
        {
            get { return "201909081229072_shopping11111"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
